# Generated by Django 3.0.3 on 2021-10-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_newpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPost',
            new_name='Post',
        ),
    ]
