# Generated by Django 3.0.3 on 2021-10-13 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20211012_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_you', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(default='profile_image/default.jpg', upload_to='profile_image')),
                ('followers', models.ManyToManyField(default=0, related_name='my_followers', to=settings.AUTH_USER_MODEL)),
                ('follows', models.ManyToManyField(default=0, related_name='people_I_follow', to=settings.AUTH_USER_MODEL)),
                ('profile_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
